### ISSUE TITLE
Flashing under Linux

### ISSUE THREAD

**Issue by derFrickler** [silver13/H8mini_blue_board#1]
Hi There,
Compiling on Ubuntu works like a a charm, but i have trouble flashing the blue H8 board.

I installed the latest openocd 0.9 and now the connection to the board works fine. 

Problem is that i need to unlock the processor and can't find the right command to do that on the blue board.

Can anyone point me to the right openocd command to unlock the processor in the blue board?

Thanks
       Johannes
http://der-frickler.net/modellbau/planes/garden_racing

**Comment by silver13** [comment]
The command to unlock should be something like this:

openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f0x.cfg -c init -c "reset halt" -c "stm32f0x unlock 0" -c "reset run" -c shutdown

may need power cycle afterwards if it does complete ok.

**Comment by derFrickler** [comment]
Thanks, that seemed to work fine!
Flashing works now!
