### ISSUE TITLE
H8 mini blue board flashing problem

### ISSUE THREAD

**Issue by Webster20002** [silver13/H8mini_blue_board#10]
Hi, I was succesfull at flashing 2 H8 mini blue boards. Then I never touched any of the needed software for over 2 months. A friend also wanted to upgrade his H8 mini and I thought it would be no problem to do that. So when I now open The Silverware throu KeilU i get the following error: registered ARM Compiler Version not found in path: ARMCC. Update the configuration of multiple ARM compiler in Manage Project Items. So I checked the Pack Installer if any software is missing but everything is up to date. Please help me to solve this issue because it is so frustrating that it doesnt work after not even using the programs. Thanks

**Comment by silver13** [comment]
I haven't seen this error, I suggest uninstalling keil and installing it again. Sorry, I can't be more helpful, certainly an unusual error as you have not even used it.

**Comment by Webster20002** [comment]
Ok thanks I will try to reinstall KeilU. I let you know if it worked.

**Comment by Webster20002** [comment]
I reinstalled KeilU and tried to build it and got over 173 errors so I also reinstalled the Silverware and now everything works fine again. Thank you very much and have a good day!

**Comment by silver13** [comment]
great
