### ISSUE TITLE
Airmode support

### ISSUE THREAD

**Issue by JamesHagerman** [silver13/H8mini_blue_board#18]
Hi there,

I know I read at one point that there was some consideration towards adding airmode support to Silverware.

I haven't taken a close enough look at the firmware PID code (or the 20 or so forks of this repo, at least) to know how complex it would be but I'd still love to know if there is any prior work towards this goal.

If no one else has dug into this, I may try my hand at implementing it.

Thanks!

**Comment by Aarons14bugs** [comment]
Air mode option would be much loved!

Switching from my 5" to my silver toys, I'm always crashing on the 1st few flights.  At least it's not the expensive ones I crash!

**Comment by silver13** [comment]
hi, sorry for late reply, the silverware code more or less has airmode built in, as long as throttle is up, so a throttle-up switch can be used tx side, or there should be a software side switch too, I can't remember the name because someone else added it

**Comment by JamesHagerman** [comment]
Ahh! Good to know! I noticed that some time this week and figured I'd try to take that approach.

I'll dig through and see if I can find reference to it.

EDIT: Ahh, I have to follow it through but this looks promising: `AIRMODE_HOLD_SWITCH`

**Comment by JamesHagerman** [comment]
Well, it's been a few months but I've finally had time to test this. With the Taranis and the multimodule, this is the config I'm using (Switches A-D across front of controller, F, and H on top where antenna is)

```
#define STARTFLIP CH_FLIP  // Switch A - chan 5
#define LEDS_ON CH_RTH // Switch B - chan 6

// rates / expert mode
#define RATES CH_PIC // Switch C - chan 7

// Airmode keeps the PID loop stabilizing the quads orientation even at zero throttle.
// To stop the motors on ground a switch on the remote control is necessary.
#define AIRMODE_HOLD_SWITCH CH_VID // Switch D - chan 8

#define LEVELMODE CH_HEADFREE // Switch F - chan 9

// Switch H is for arming but I don't remember how I set that up.
```

And it mostly works: when the throttle is down and the air mode channel is off, the quad tries to maintain it's orientation both in acro and level mode. When that same channel is on, it acts as a motor kill switch.

What's unexpected is the rates are pretty low. Even when using the `RATES` channel.

But then again, maybe my rates are just too low and I should be adjusting my curves...

**Comment by JamesHagerman** [comment]
Ah ha! That was it! My rates were too low. These at least allow me to flip reasonably quick while still having a reasonable amount of control.

```
// rate in deg/sec
// for acro mode
#define MAX_RATE 720.0
#define MAX_RATEYAW 720.0

// max angle for level mode
#define MAX_ANGLE_HI 70.0f

#define LOW_RATES_MULTI 0.25f
```

I also setup "Insert Before" input curves with weights of 100 and expo set at 50 (for everything but throttle) in OpenTX following the directions on this site:
https://www.rcgroups.com/forums/showthread.php?2825806-Q-X7-with-OpenTX-Rates-and-Expo

And it's good enough!

Thank you!
