### ISSUE TITLE
Unable to unlock using openocd on linux

### ISSUE THREAD

**Issue by vinz486** [silver13/H8mini_blue_board#4]
Hi,
I'm trying to flash using Ubuntu and openocd 0.9.0

I copied unlock commad from non-blue board readme, changing the CPU id to the right one:

`vinz@bookz:~/H8mini_blue_board/bin$ openocd -s /usr/share/openocd/scripts -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f0x.cfg  -c init -c "reset halt" -c "mww 0x40022004 0x45670123" -c "mww 0x40022004 0xCDEF89AB" -c "mww 0x40022008 0x45670123" -c "mww 0x40022008 0xCDEF89AB" -c "mww 0x40022010 0x220" -c "mww 0x40022010 0x260" -c "sleep 100" -c "mww 0x40022010 0x230" -c "mwh 0x1ffff800 0x5AA5" -c "sleep 1000" -c "mww 0x40022010 0x2220" -c "sleep 100" -c "mdw 0x40022010" -c "mdw 0x4002201c" -c "mdw 0x1ffff800"

Open On-Chip Debugger 0.9.0 (2015-09-02-10:42)

Licensed under GNU GPL v2

adapter speed: 1000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v21 API v2 SWIM v4 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.232718
Info : stm32f0x.cpu: hardware has 4 breakpoints, 2 watchpoints
target state: halted
target halted due to debug-request, current mode: Handler HardFault
xPSR: 0xc1000003 pc: 0xfffffffe msp: 0xfffffffc
`
But it's not working.

I tried to flash anyway but i got errot:

`vinz@bookz:~/H8mini_blue_board/bin$ openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f0x.cfg -c init -c "reset halt" -c "flash write_image erase h8blue_keil_devo.bin 0x08000000" -c "verify_image h8mini 0x08000000" -c "reset run" -c shutdownOpen On-Chip Debugger 0.9.0 (2015-09-02-10:42)
Licensed under GNU GPL v2

adapter speed: 1000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v21 API v2 SWIM v4 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.226877
Info : stm32f0x.cpu: hardware has 4 breakpoints, 2 watchpoints
target state: halted
target halted due to debug-request, current mode: Handler HardFault
xPSR: 0xc1000003 pc: 0xfffffffe msp: 0xfffffffc
auto erase enabled
Info : device id = 0x10006444
Info : flash size = 16kbytes
Error: stm32x device protected
Error: failed erasing sectors 0 to 10
`
Can you help me and insert in the readme the linux command line to flash this blue version?

**Comment by silver13** [comment]
the command to unlock / flash should be correct in the file https://github.com/silver13/H8mini_blue_board/blob/master/INSTALL.md

The line you have tried is for the gd32f130 cpu, which for some reason needs slightly different timing. But it's cortex m3, so it probably failed because the blue board is M0

**Comment by vinz486** [comment]
Just flashed successful following INSTALL md. Thanks.
