### ISSUE TITLE
Target not created.

### ISSUE THREAD

**Issue by Maniacsh** [silver13/H8mini_blue_board#6]
Hi there,

I think I'm very close. When I click Build target (F7), I get this error in the log:

`.\Objects\h8blue.axf: Error: L6218E: Undefined symbol rgb_init (referred from main.o).`
`Not enough information to list image symbols.`
`Finished: 1 information, 0 warning and 1 error messages.`
`".\Objects\h8blue.axf" - 1 Error(s), 0 Warning(s).`
`Target not created.`

I tried other projects and build them, which succeeded fine. :(

**Comment by silver13** [comment]
sorry about this, seems the files on my computer and those on the server have become out of sync

It should be fixed now, thanks for your error report
