### ISSUE TITLE
How do the flips with this firmware?

### ISSUE THREAD

**Issue by MathijsG** [silver13/H8mini_blue_board#7]
I flashed this firmware, because I like to have the ability flying with acro mode.

However I was wondering how I can do the flips on level mode again? The method I used with the stock firmware doesn't do anything anymore.

I'm using the stock transmitter.

**Comment by silver13** [comment]
the flip functionality was to be removed from this, however, it's still here:

To enable, set a channel for the flip function in config.h:
`#define STARTFLIP CH_FLIP`

This should work on the stock tx

Then comment this line to enable the flip code:
```
// Flash saving features
#define DISABLE_HEADLESS
//#define DISABLE_FLIP_SEQUENCER
```

Please download the latest code as I fixed a bug in it

**Comment by MathijsG** [comment]
Why is the flip functionality to be removed anyway :)?

And how do I know which button is which channel? Or will it be the default one with just the pieces of code you posted above?

**Comment by silver13** [comment]
The line posted is for the flip button of the stock tx.

The main reason was that it was somewhat complicated on the h101 which also has inverted flight, so I removed it there. It seems to work ok now, but it's not really used much to my knowledge as acro mode makes it kind of unnecessary
